# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'J:\Projects\FileTransferSystem\SecureFileTransfe\PageAfterLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 600)
        MainWindow.setMinimumSize(QtCore.QSize(850, 600))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("#frame{\n"
"    \n"
"    background-color: rgb(19, 99, 119);\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame_top.sizePolicy().hasHeightForWidth())
        self.frame_top.setSizePolicy(sizePolicy)
        self.frame_top.setStyleSheet("#frame_top{\n"
"    \n"
"    background-color: rgb(252, 236, 12);\n"
"\n"
"}")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.frame_4 = QtWidgets.QFrame(self.frame_top)
        self.frame_4.setGeometry(QtCore.QRect(740, -10, 82, 44))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255,0);\n"
"boder:none;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/ico/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255,0);\n"
"boder:none;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/ico/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.frame_top)
        self.frame_content = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(95)
        sizePolicy.setHeightForWidth(self.frame_content.sizePolicy().hasHeightForWidth())
        self.frame_content.setSizePolicy(sizePolicy)
        self.frame_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_content)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_left = QtWidgets.QFrame(self.frame_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_left.sizePolicy().hasHeightForWidth())
        self.frame_left.setSizePolicy(sizePolicy)
        self.frame_left.setStyleSheet("#frame_left{\n"
"    \n"
"    background-color: rgb(8, 74, 90);\n"
"\n"
"}")
        self.frame_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left.setObjectName("frame_left")
        self.frame_operate = QtWidgets.QFrame(self.frame_left)
        self.frame_operate.setGeometry(QtCore.QRect(0, 110, 171, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_operate.sizePolicy().hasHeightForWidth())
        self.frame_operate.setSizePolicy(sizePolicy)
        self.frame_operate.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_operate.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_operate.setBaseSize(QtCore.QSize(0, 10))
        self.frame_operate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_operate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_operate.setLineWidth(0)
        self.frame_operate.setObjectName("frame_operate")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_operate)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 15)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_transfer = QtWidgets.QPushButton(self.frame_operate)
        self.pushButton_transfer.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_transfer.sizePolicy().hasHeightForWidth())
        self.pushButton_transfer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("851tegakizatsu")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_transfer.setFont(font)
        self.pushButton_transfer.setStyleSheet("\n"
"QPushButton{    border-radius:30px;\n"
"color: rgb(248, 237, 83);\n"
"}\n"
"QPushButton:pressed{    \n"
"image: url(:/ico/ico/cutbutton.png);\n"
"}")
        self.pushButton_transfer.setCheckable(False)
        self.pushButton_transfer.setObjectName("pushButton_transfer")
        self.verticalLayout_2.addWidget(self.pushButton_transfer)
        self.pushButton_log = QtWidgets.QPushButton(self.frame_operate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_log.sizePolicy().hasHeightForWidth())
        self.pushButton_log.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("851tegakizatsu")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_log.setFont(font)
        self.pushButton_log.setStyleSheet("\n"
"QPushButton{    border-radius:30px;\n"
"color: rgb(248, 237, 83);\n"
"}\n"
"QPushButton:pressed{    \n"
"image: url(:/ico/ico/cutbutton.png);\n"
"}")
        self.pushButton_log.setCheckable(True)
        self.pushButton_log.setChecked(False)
        self.pushButton_log.setAutoExclusive(True)
        self.pushButton_log.setAutoDefault(False)
        self.pushButton_log.setDefault(False)
        self.pushButton_log.setObjectName("pushButton_log")
        self.verticalLayout_2.addWidget(self.pushButton_log)
        self.pushButton_info = QtWidgets.QPushButton(self.frame_operate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_info.sizePolicy().hasHeightForWidth())
        self.pushButton_info.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("851tegakizatsu")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_info.setFont(font)
        self.pushButton_info.setStyleSheet("\n"
"QPushButton{    border-radius:30px;\n"
"color: rgb(248, 237, 83);\n"
"}\n"
"QPushButton:pressed{    \n"
"image: url(:/ico/ico/cutbutton.png);\n"
"}")
        self.pushButton_info.setObjectName("pushButton_info")
        self.verticalLayout_2.addWidget(self.pushButton_info)
        self.label_back = QtWidgets.QLabel(self.frame_left)
        self.label_back.setGeometry(QtCore.QRect(0, 10, 91, 61))
        self.label_back.setStyleSheet("image: url(:/ico/ico/redpoint2.png);")
        self.label_back.setText("")
        self.label_back.setObjectName("label_back")
        self.label_user = QtWidgets.QLabel(self.frame_left)
        self.label_user.setGeometry(QtCore.QRect(80, 0, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.label_user.setFont(font)
        self.label_user.setStyleSheet("color: rgb(248, 237, 83);")
        self.label_user.setObjectName("label_user")
        self.frame_connect = QtWidgets.QFrame(self.frame_left)
        self.frame_connect.setGeometry(QtCore.QRect(20, 470, 121, 51))
        self.frame_connect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_connect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_connect.setObjectName("frame_connect")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_connect)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_connect_light = QtWidgets.QLabel(self.frame_connect)
        self.label_connect_light.setStyleSheet("image: url(:/ico/ico/greenpoint.png);")
        self.label_connect_light.setText("")
        self.label_connect_light.setObjectName("label_connect_light")
        self.horizontalLayout_5.addWidget(self.label_connect_light)
        self.label_connect = QtWidgets.QLabel(self.frame_connect)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_connect.setFont(font)
        self.label_connect.setStyleSheet("color: rgb(248, 237, 83);")
        self.label_connect.setObjectName("label_connect")
        self.horizontalLayout_5.addWidget(self.label_connect)
        self.frame_net = QtWidgets.QFrame(self.frame_left)
        self.frame_net.setGeometry(QtCore.QRect(30, 400, 111, 71))
        self.frame_net.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_net.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_net.setObjectName("frame_net")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_net)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_ip = QtWidgets.QLabel(self.frame_net)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_ip.setFont(font)
        self.label_ip.setStyleSheet("color: rgb(248, 237, 83);")
        self.label_ip.setObjectName("label_ip")
        self.verticalLayout_4.addWidget(self.label_ip)
        self.label_port = QtWidgets.QLabel(self.frame_net)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_port.setFont(font)
        self.label_port.setStyleSheet("color: rgb(248, 237, 83);")
        self.label_port.setObjectName("label_port")
        self.verticalLayout_4.addWidget(self.label_port)
        self.label_user_identity = QtWidgets.QLabel(self.frame_left)
        self.label_user_identity.setGeometry(QtCore.QRect(90, 40, 61, 31))
        font = QtGui.QFont()
        font.setFamily("851tegakizatsu")
        font.setPointSize(12)
        self.label_user_identity.setFont(font)
        self.label_user_identity.setStyleSheet("\n"
"color: rgb(248, 237, 83);")
        self.label_user_identity.setObjectName("label_user_identity")
        self.label_10 = QtWidgets.QLabel(self.frame_left)
        self.label_10.setGeometry(QtCore.QRect(30, 20, 31, 31))
        self.label_10.setStyleSheet("image: url(:/ico/ico/user1.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.frame_left)
        self.frame_right = QtWidgets.QFrame(self.frame_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_right.sizePolicy().hasHeightForWidth())
        self.frame_right.setSizePolicy(sizePolicy)
        self.frame_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_right.setObjectName("frame_right")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_right)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_right_top = QtWidgets.QFrame(self.frame_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_right_top.sizePolicy().hasHeightForWidth())
        self.frame_right_top.setSizePolicy(sizePolicy)
        self.frame_right_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_right_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_right_top.setObjectName("frame_right_top")
        self.label_4 = QtWidgets.QLabel(self.frame_right_top)
        self.label_4.setGeometry(QtCore.QRect(90, 0, 491, 81))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(35)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(248, 237, 83);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.frame_right_top)
        self.frame_right_bottom = QtWidgets.QFrame(self.frame_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.frame_right_bottom.sizePolicy().hasHeightForWidth())
        self.frame_right_bottom.setSizePolicy(sizePolicy)
        self.frame_right_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_right_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_right_bottom.setObjectName("frame_right_bottom")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_right_bottom)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_right_bottom)
        self.stackedWidget.setStyleSheet("background-color: rgba(0, 0, 0,0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_transfer = QtWidgets.QWidget()
        self.page_transfer.setObjectName("page_transfer")
        self.pushButton_upload = QtWidgets.QPushButton(self.page_transfer)
        self.pushButton_upload.setGeometry(QtCore.QRect(110, 300, 111, 41))
        font = QtGui.QFont()
        font.setFamily("851tegakizatsu")
        font.setPointSize(15)
        self.pushButton_upload.setFont(font)
        self.pushButton_upload.setStyleSheet("\n"
"QPushButton{    \n"
"background-color: rgb(207, 44, 24);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_upload.setObjectName("pushButton_upload")
        self.pushButton_download = QtWidgets.QPushButton(self.page_transfer)
        self.pushButton_download.setGeometry(QtCore.QRect(370, 300, 111, 41))
        font = QtGui.QFont()
        font.setFamily("851tegakizatsu")
        font.setPointSize(15)
        self.pushButton_download.setFont(font)
        self.pushButton_download.setStyleSheet("\n"
"QPushButton{    \n"
"background-color: rgb(207, 44, 24);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_download.setObjectName("pushButton_download")
        self.tableWidget = QtWidgets.QTableWidget(self.page_transfer)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 641, 261))
        self.tableWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"color:rgba(255, 255, 255,100);\n"
"    font: 12pt \"黑体\";\n"
"background:rgba(8, 74, 90,100);\n"
"border:0px solid #242424;\n"
"alternate-background-color:rgba(10, 113, 139,100);\n"
"gridline-color:rgba(8, 74, 90,100);\n"
"}\n"
" \n"
"QTableWidget::item:selected{\n"
"color:#DCDCDC;\n"
"background: rgb(223, 212, 63);\n"
"}\n"
" \n"
"QTableWidget::item:hover{\n"
"background:rgb(88, 72, 44);;\n"
"}\n"
"QHeaderView::section{\n"
"text-align:center;\n"
"background:rgb(88, 72, 44);\n"
"padding:3px;\n"
"margin:0px;\n"
"color:#DCDCDC;\n"
"border:1px solid #242424;\n"
"border-left-width:0;\n"
"}\n"
" \n"
"QScrollBar:vertical{\n"
"background:#484848;\n"
"padding:0px;\n"
"border-radius:6px;\n"
"max-width:12px;\n"
"}\n"
" \n"
" \n"
"QScrollBar::handle:vertical{\n"
"background:#CCCCCC;\n"
"}\n"
" \n"
"QScrollBar::handle:hover:vertical,QScrollBar::handle:pressed:vertical{\n"
"background:#A7A7A7;\n"
"}\n"
"QScrollBar::sub-page:vertical{\n"
"background:#444444;\n"
"}\n"
" \n"
" \n"
"QScrollBar::add-page:vertical{\n"
"background:#5B5B5B;\n"
"}\n"
" \n"
"\n"
"")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.stackedWidget.addWidget(self.page_transfer)
        self.page_log = QtWidgets.QWidget()
        self.page_log.setObjectName("page_log")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.page_log)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 40, 611, 341))
        self.tableWidget_2.setStyleSheet("QTableWidget{\n"
"color:#DCDCDC;\n"
"background:#444444;\n"
"border:1px solid #242424;\n"
"alternate-background-color:#525252;\n"
"gridline-color:#242424;\n"
"}\n"
" \n"
"QTableWidget::item:selected{\n"
"color:#DCDCDC;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
" \n"
"QTableWidget::item:hover{\n"
"background:#5B5B5B;\n"
"}\n"
"QHeaderView::section{\n"
"text-align:center;\n"
"background:#5E5E5E;\n"
"padding:3px;\n"
"margin:0px;\n"
"color:#DCDCDC;\n"
"border:1px solid #242424;\n"
"border-left-width:0;\n"
"}\n"
" \n"
"QScrollBar:vertical{\n"
"background:#484848;\n"
"padding:0px;\n"
"border-radius:6px;\n"
"max-width:12px;\n"
"}\n"
" \n"
" \n"
"QScrollBar::handle:vertical{\n"
"background:#CCCCCC;\n"
"}\n"
" \n"
"QScrollBar::handle:hover:vertical,QScrollBar::handle:pressed:vertical{\n"
"background:#A7A7A7;\n"
"}\n"
"QScrollBar::sub-page:vertical{\n"
"background:#444444;\n"
"}\n"
" \n"
" \n"
"QScrollBar::add-page:vertical{\n"
"background:#5B5B5B;\n"
"}\n"
" \n"
"QScrollBar::add-line:vertical{\n"
"background:none;\n"
"}\n"
"QScrollBar::sub-line:vertical{\n"
"background:none;\n"
"}")
        self.tableWidget_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_2.setDragDropOverwriteMode(True)
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setShowGrid(False)
        self.tableWidget_2.setRowCount(15)
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setObjectName("tableWidget_2")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.tableWidget_2.horizontalHeader().setVisible(False)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setStretchLastSection(False)
        self.stackedWidget.addWidget(self.page_log)
        self.horizontalLayout_4.addWidget(self.stackedWidget)
        self.verticalLayout_3.addWidget(self.frame_right_bottom)
        self.horizontalLayout_3.addWidget(self.frame_right)
        self.frame_right.raise_()
        self.frame_left.raise_()
        self.verticalLayout.addWidget(self.frame_content)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(MainWindow.showMinimized)
        self.pushButton_2.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_transfer.setText(_translate("MainWindow", "文件传输"))
        self.pushButton_log.setText(_translate("MainWindow", "日志查看"))
        self.pushButton_info.setText(_translate("MainWindow", "软件信息"))
        self.label_user.setText(_translate("MainWindow", "Superyu"))
        self.label_connect.setText(_translate("MainWindow", "Connected"))
        self.label_ip.setText(_translate("MainWindow", "IP:10.191.1.1"))
        self.label_port.setText(_translate("MainWindow", "Port:6666"))
        self.label_user_identity.setText(_translate("MainWindow", "管理员"))
        self.label_4.setText(_translate("MainWindow", "Secure File Transfer"))
        self.pushButton_upload.setText(_translate("MainWindow", "上传"))
        self.pushButton_download.setText(_translate("MainWindow", "下载"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "文件名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "文件大小"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "上传用户"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "时间"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "用户"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "操作"))
import ico_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
